// Regenerates generated.ts from the skill source files in this directory.
// Run this any time a file under packages/agent/skills/builtin/<skill>/ changes.
//
// Why generated at build time instead of read from disk at runtime: these files
// need to be available inside the *user's sandbox*, written there by server code
// running in a Vercel serverless function. Next.js's output file tracer does not
// reliably bundle arbitrary directories read via fs at runtime, so we inline the
// contents as string literals in a real TS module, which the tracer always
// includes since it's a static import.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = fileURLToPath(new URL(".", import.meta.url));

function walk(base, current = "") {
  const entries = readdirSync(join(base, current));
  const files = [];
  for (const entry of entries) {
    const rel = current ? `${current}/${entry}` : entry;
    const full = join(base, rel);
    if (statSync(full).isDirectory()) {
      files.push(...walk(base, rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

const skillNames = readdirSync(dir).filter((name) =>
  statSync(join(dir, name)).isDirectory(),
);

const skills = skillNames.map((name) => {
  const skillDir = join(dir, name);
  const files = walk(skillDir).sort();
  const fileEntries = files.map((relPath) => {
    const content = readFileSync(join(skillDir, relPath), "utf-8");
    return [relPath, content];
  });
  return { name, files: fileEntries };
});

const skillBlocks = skills.map((skill) => {
  const fileLines = skill.files
    .map(
      ([relPath, content]) =>
        `      ${JSON.stringify(relPath)}: ${JSON.stringify(content)},`,
    )
    .join("\n");
  return [
    "  {",
    `    name: ${JSON.stringify(skill.name)},`,
    "    files: {",
    fileLines,
    "    },",
    "  },",
  ].join("\n");
});

const lines = [
  "// AUTO-GENERATED by generate.mjs. Do not edit by hand.",
  "// Regenerate with: node packages/agent/skills/builtin/generate.mjs",
  "",
  "export interface BuiltinSkill {",
  "  name: string;",
  "  /** Map of file path (relative to the skill's own directory) to file content. */",
  "  files: Record<string, string>;",
  "}",
  "",
  "export const BUILTIN_SKILLS: BuiltinSkill[] = [",
  skillBlocks.join("\n"),
  "];",
  "",
];

writeFileSync(join(dir, "generated.ts"), lines.join("\n"));
console.log(
  `Wrote generated.ts with ${skills.length} skill(s): ${skills
    .map((s) => `${s.name} (${s.files.length} files)`)
    .join(", ")}`,
);
