import { SignInButton } from "@/components/auth/sign-in-button";

type BentoItem = { readonly id: string; readonly title: string; readonly body: string; readonly tag: string };
const items: readonly BentoItem[] = [
  { id: "01", title: "AI SDK", tag: "model layer", body: "One clean interface for streaming, tools, and switching models without rewriting the agent." },
  { id: "02", title: "Entry Gateway", tag: "routing layer", body: "A single control plane for provider routing, fallbacks, rate limits, and observability." },
  { id: "03", title: "Sandbox", tag: "runtime layer", body: "A private, disposable machine for every session with the filesystem and network access work needs." },
  { id: "04", title: "Lightflow SDK", tag: "durability layer", body: "Long-running workflows that checkpoint, retry, and reconnect instead of disappearing mid-task." },
];

export function LandingBento() {
  return <section id="stack" className="mx-auto max-w-[1320px] px-6 sm:px-0"><div className="border-t border-(--l-border) px-0 py-5 sm:px-10"><div className="flex justify-between text-[10px] font-semibold uppercase tracking-[0.16em] text-(--l-fg-3)"><span>03 / The stack</span><span className="hidden sm:inline">The advantage is the system</span></div></div><div className="border-y border-(--l-border) bg-(--l-surface)"><div className="grid gap-10 px-6 py-16 sm:px-10 md:grid-cols-[1fr_.8fr] md:py-24"><div><p className="font-mono text-[10px] uppercase text-(--l-accent)">One opinionated system</p><h2 className="mt-6 max-w-2xl text-balance text-5xl font-medium leading-[.88] tracking-[-.075em] sm:text-7xl">The parts are<br /><span className="text-(--l-accent)">better together.</span></h2></div><div className="flex flex-col items-start justify-between gap-8"><p className="max-w-md text-pretty text-lg leading-relaxed text-(--l-fg-2)">Serious infrastructure for teams that want to move at startup speed without treating production like a prototype.</p><SignInButton /></div></div><div className="grid border-t border-(--l-border) md:grid-cols-2 lg:grid-cols-4">{items.map((item) => <article key={item.id} className="group border-b border-(--l-border) p-6 transition-colors hover:bg-(--l-accent) hover:text-white sm:p-10 lg:border-b-0 lg:border-r last:lg:border-r-0"><div className="flex items-center justify-between font-mono text-[10px] text-(--l-accent) group-hover:text-white"><span>{item.id}</span><span>{item.tag}</span></div><h3 className="mt-16 text-2xl font-medium tracking-[-.05em]">{item.title}</h3><p className="mt-4 text-sm leading-relaxed text-(--l-fg-2) group-hover:text-white/80">{item.body}</p></article>)}</div></div></section>;
}
